### ISSUE TITLE
Crashing issue with Group pages

### ISSUE THREAD

**Issue by kylehuynh205** [digitalutsc/islandora_breadcrumbs#15]
## How to reproduce

* Have the module enabled and configure in isle-dc 
* Visit Groups > Create a new group (if no group created yet) > Select a group > Members
* White screen of death appears
* Log messages:
````
#0 /var/www/drupal/web/core/lib/Drupal/Core/Routing/UrlGenerator.php(207): preg_match()
#1 /var/www/drupal/web/core/lib/Drupal/Core/Routing/UrlGenerator.php(256): Drupal\Core\Routing\UrlGenerator->doGenerate()
#2 /var/www/drupal/web/core/lib/Drupal/Core/Routing/UrlGenerator.php(300): Drupal\Core\Routing\UrlGenerator->getInternalPathFromRoute()
#3 /var/www/drupal/web/core/lib/Drupal/Core/Render/MetadataBubblingUrlGenerator.php(108): Drupal\Core\Routing\UrlGenerator->generateFromRoute()
#4 /var/www/drupal/web/core/lib/Drupal/Core/Url.php(765): Drupal\Core\Render\MetadataBubblingUrlGenerator->generateFromRoute()
#5 /var/www/drupal/web/modules/contrib/islandora_breadcrumbs/islandora_breadcrumbs.module(37): Drupal\Core\Url->toString()
#6 [internal function]: islandora_breadcrumbs_preprocess_islandora_breadcrumb()
#7 /var/www/drupal/web/core/lib/Drupal/Core/Theme/ThemeManager.php(261): call_user_func_array()
#8 /var/www/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(480): Drupal\Core\Theme\ThemeManager->render()
#9 /var/www/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(240): Drupal\Core\Render\Renderer->doRender()
#10 /var/www/drupal/web/core/lib/Drupal/Core/Template/TwigExtension.php(475): Drupal\Core\Render\Renderer->render()
#11 /var/www/drupal/web/sites/default/files/php/twig/65c2462eaba57_block.html.twig_py8BT1vpyypu6prgs8JbPMRYc/n_cZYKY5mjX5nq1Vlli0a1rdcLww5YytdznfdJRIAhE.php(91): Drupal\Core\Template\TwigExtension->escapeFilter()
#12 /var/www/drupal/vendor/twig/twig/src/Template.php(171): __TwigTemplate_f96f14376e9972846e9dbdc67185df10->block_content()
#13 /var/www/drupal/web/sites/default/files/php/twig/65c2462eaba57_block.html.twig_py8BT1vpyypu6prgs8JbPMRYc/n_cZYKY5mjX5nq1Vlli0a1rdcLww5YytdznfdJRIAhE.php(74): Twig\Template->displayBlock()
#14 /var/www/drupal/vendor/twig/twig/src/Template.php(394): __TwigTemplate_f96f14376e9972846e9dbdc67185df10->doDisplay()
#15 /var/www/drupal/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#16 /var/www/drupal/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#17 /var/www/drupal/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render()
#18 /var/www/drupal/web/core/themes/engines/twig/twig.engine(39): Twig\TemplateWrapper->render()
#19 /var/www/drupal/web/core/lib/Drupal/Core/Theme/ThemeManager.php(348): twig_render_template()
#20 /var/www/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(480): Drupal\Core\Theme\ThemeManager->render()
#21 /var/www/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(493): Drupal\Core\Render\Renderer->doRender()
#22 /var/www/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(240): Drupal\Core\Render\Renderer->doRender()
#23 /var/www/drupal/web/core/lib/Drupal/Core/Template/TwigExtension.php(475): Drupal\Core\Render\Renderer->render()
#24 /var/www/drupal/web/sites/default/files/php/twig/65c2462eaba57_page.html.twig_IjgttCBRYScOwH6EdVvPvOwG-/otFrOR4nNvKCd69-b-DYuuqnC8b29WNo91drwycT42w.php(128): Drupal\Core\Template\TwigExtension->escapeFilter()
#25 /var/www/drupal/vendor/twig/twig/src/Template.php(394): __TwigTemplate_4d1e6b6c399a93e723200571be34b03c->doDisplay()
#26 /var/www/drupal/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#27 /var/www/drupal/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#28 /var/www/drupal/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render()
#29 /var/www/drupal/web/core/themes/engines/twig/twig.engine(39): Twig\TemplateWrapper->render()
#30 /var/www/drupal/web/core/lib/Drupal/Core/Theme/ThemeManager.php(348): twig_render_template()
#31 /var/www/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(480): Drupal\Core\Theme\ThemeManager->render()
#32 /var/www/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(240): Drupal\Core\Render\Renderer->doRender()
#33 /var/www/drupal/web/core/lib/Drupal/Core/Template/TwigExtension.php(475): Drupal\Core\Render\Renderer->render()
#34 /var/www/drupal/web/sites/default/files/php/twig/65c2462eaba57_html.html.twig_xOAfYYQcJLg0kkw1m1KGxRAOG/NfxHK_eIw6LNDEzey1k_zI3Fo4iKTx8XfWOTwIMc62k.php(93): Drupal\Core\Template\TwigExtension->escapeFilter()
#35 /var/www/drupal/vendor/twig/twig/src/Template.php(394): __TwigTemplate_34c72ad3e378b9561bc22d12ece472d8->doDisplay()
#36 /var/www/drupal/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#37 /var/www/drupal/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#38 /var/www/drupal/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render()
#39 /var/www/drupal/web/core/themes/engines/twig/twig.engine(39): Twig\TemplateWrapper->render()
#40 /var/www/drupal/web/core/lib/Drupal/Core/Theme/ThemeManager.php(348): twig_render_template()
#41 /var/www/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(480): Drupal\Core\Theme\ThemeManager->render()
#42 /var/www/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(240): Drupal\Core\Render\Renderer->doRender()
#43 /var/www/drupal/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(158): Drupal\Core\Render\Renderer->render()
#44 /var/www/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(627): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}()
#45 /var/www/drupal/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(153): Drupal\Core\Render\Renderer->executeInRenderContext()
#46 /var/www/drupal/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse()
#47 [internal function]: Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray()
#48 /var/www/drupal/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func()
#49 /var/www/drupal/vendor/symfony/http-kernel/HttpKernel.php(186): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch()
#50 /var/www/drupal/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#51 /var/www/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle()
#52 /var/www/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle()
#53 /var/www/drupal/web/core/lib/Drupal/Core/StackMiddleware/ContentLength.php(28): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#54 /var/www/drupal/web/core/modules/big_pipe/src/StackMiddleware/ContentLength.php(32): Drupal\Core\StackMiddleware\ContentLength->handle()
#55 /var/www/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\big_pipe\StackMiddleware\ContentLength->handle()
#56 /var/www/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#57 /var/www/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle()
#58 /var/www/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#59 /var/www/drupal/web/core/lib/Drupal/Core/StackMiddleware/AjaxPageState.php(36): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#60 /var/www/drupal/web/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\AjaxPageState->handle()
#61 /var/www/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(704): Drupal\Core\StackMiddleware\StackedHttpKernel->handle()
#62 /var/www/drupal/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#63 {main}
````

## Temporary solution
* Disable the breadcrumb block

**Comment by HyphenHook** [comment]
# Issue
- Islandora Breadcrumb is functioning in all pages which results in some pages passing in invalid objects to the preprocess function which leads to the crash. (e.g group page causes a group object being passed in instead of an url)

# Solution
- Restrict Islandora Breadcrumb to function only within islandora_object type nodes.
